@ConsoleCatalog.Server_HostAddress = http://localhost:5162


GET {{ConsoleCatalog.Server_HostAddress}}/user/getUserByUsername/
Accept: application/json

###

GET {{ConsoleCatalog.Server_HostAddress}}/user/getUserById/
Accept: application/json

###

POST {{ConsoleCatalog.Server_HostAddress}}/user/
Accept: application/json

###

POST {{ConsoleCatalog.Server_HostAddress}}/objectives/postSubObjective/
Accept: application/json

###

POST {{ConsoleCatalog.Server_HostAddress}}/objectives/postSubObjectives/
Accept: application/json

###

GET {{ConsoleCatalog.Server_HostAddress}}/objectives/getSubObjective/
Accept: application/json

###

GET {{ConsoleCatalog.Server_HostAddress}}/objectives/getSubObjectives/
Accept: application/json

###

DELETE {{ConsoleCatalog.Server_HostAddress}}/objectives/deleteSubObjective/
Accept: application/json

###

DELETE {{ConsoleCatalog.Server_HostAddress}}/objectives/deleteSubObjectives/
Accept: application/json

###

GET {{ConsoleCatalog.Server_HostAddress}}/playstation/getProfileById/
Accept: application/json

###

GET {{ConsoleCatalog.Server_HostAddress}}/playstation/getProfileByOnlineId/
Accept: application/json

###

GET {{ConsoleCatalog.Server_HostAddress}}/playstation/getProfileByAccountId/
Accept: application/json

###

POST {{ConsoleCatalog.Server_HostAddress}}/playstation/postProfile/
Accept: application/json

###

PUT {{ConsoleCatalog.Server_HostAddress}}/playstation/putProfile/
Accept: application/json

###

GET {{ConsoleCatalog.Server_HostAddress}}/playstation/getProfileTitles/
Accept: application/json